"""GEO agent — venue discovery: WHERE the brand should show up, by name and URL.

The action plan used to say things like "grow third-party mentions", which is
advice, not a plan: nobody can open it on Monday and do it. The reason was not
the strategist model — it was that the strategist had nothing venue-shaped to
work from. It saw the brand's own rates and a list of cited domains, so a list
of cited domains and a platitude is what it could write.

This module produces the missing evidence: real subreddits, forums, listicle
publishers, review platforms and channels, each with a URL that resolves,
discovered two ways —

  1. **From our own measurements.** ``source_gap`` is the strongest signal we
     own: domains the engines cited on our tracked questions in answers where
     the brand was absent. Those venues demonstrably feed the answers we lose.
  2. **From live search.** Serper queries per venue kind, so the plan can name
     communities and round-ups that no citation happened to surface.

Nothing here is generated by a model. Asking an LLM to name subreddits reliably
produces plausible ones that do not exist, and a plan whose first step is a dead
link is worse than no plan — so the strategist is handed this list and told it
may not invent venues outside it (``geo_strategy`` enforces that on the way out).
"""
from __future__ import annotations

import re
from collections import defaultdict
from typing import Any, Callable

from seo_geo_agent.sources import CredentialMissing, domain_of, serper_search

# Venue kinds, ordered by how directly presence there tends to move AI answers.
KIND_COMMUNITY = "community"
KIND_LISTICLE = "listicle"
KIND_REVIEW = "review"
KIND_FORUM = "forum"
KIND_VIDEO = "video"

# Review platforms worth a presence check for B2B brands. Presence is an
# inclusion requirement for engines that read them; review COUNT is not, and
# this module deliberately does not chase it.
REVIEW_PLATFORMS = ("g2.com", "capterra.com", "trustradius.com", "getapp.com")

# One Serper call per query. Kept small because these are paid and the marginal
# venue after the first page is rarely worth the spend.
_MAX_EXAMPLES = 4
_SUBREDDIT_RE = re.compile(r"reddit\.com/r/([A-Za-z0-9_]+)", re.I)


def _category_terms(brand: dict, prompts: list[dict]) -> str:
    """The phrase we search venues for. Brand seeds are the curated answer;
    prompt text is the fallback when a brand has none."""
    seeds = [s for s in (brand.get("seeds") or []) if s]
    if seeds:
        return seeds[0]
    for prompt in prompts:
        text = (prompt.get("text") or "").strip()
        if text:
            # strip the question framing so the query reads like a topic
            return re.sub(r"^(what|which|who|how|best|top)\b\s*", "", text, flags=re.I)[:80]
    return brand.get("name", "")


def _subreddit_of(url: str) -> str:
    match = _SUBREDDIT_RE.search(url or "")
    return f"r/{match.group(1)}" if match else ""


def _queries(brand: dict, category: str) -> list[tuple[str, str]]:
    """(kind, query) pairs. One Serper call each, so this list IS the budget."""
    name = brand.get("name", "")
    sites = " OR ".join("site:" + platform for platform in REVIEW_PLATFORMS)
    return [
        (KIND_COMMUNITY, f"site:reddit.com {category}"),
        (KIND_LISTICLE, f"best {category}"),
        (KIND_LISTICLE, f"top {category} providers"),
        (KIND_FORUM, f"site:quora.com {category}"),
        (KIND_VIDEO, f"site:youtube.com {category}"),
        (KIND_REVIEW, f"{name} reviews {sites}"),
    ]


def _venue_key(kind: str, name: str) -> str:
    return f"{kind}:{name.lower()}"


def discover(
    brand: dict,
    prompts: list[dict],
    report: dict,
    *,
    search: Callable[[str], dict] = serper_search,
    max_queries: int = 6,
) -> dict:
    """Real, addressable venues for this brand's category.

    Never raises on a dead search: a venue list built from citations alone is
    still a usable plan, and a 503 here would take the whole Action Plan down
    with it. What failed is reported in ``searched``/``errors`` so the panel can
    say the list is partial rather than implying it is complete.
    """
    category = _category_terms(brand, prompts)
    own_domain = (brand.get("domain") or "").lower().removeprefix("www.")
    venues: dict[str, dict] = {}
    errors: list[str] = []
    searched = 0

    # ---- 1. measured: domains the engines already cite where we are absent ----
    for gap in (report.get("source_gap") or [])[:12]:
        domain = gap.get("domain", "")
        if not domain or domain == own_domain:
            continue
        kind = KIND_REVIEW if domain in REVIEW_PLATFORMS else KIND_LISTICLE
        venues[_venue_key(kind, domain)] = {
            "kind": kind,
            "name": domain,
            "url": f"https://{domain}",
            "cited_where_absent": int(gap.get("count") or 0),
            "found_via": ["engine-citations"],
            "examples": [],
        }

    # ---- 2. live: what actually exists for this category right now ----
    for kind, query in _queries(brand, category)[:max_queries]:
        try:
            result = search(query)
            searched += 1
        except CredentialMissing as exc:
            errors.append(f"{kind}: search unavailable ({exc})")
            continue
        except Exception as exc:  # noqa: BLE001 — a dead query must not kill the list
            errors.append(f"{kind}: {type(exc).__name__}: {exc}")
            continue
        for hit in result.get("organic", []):
            url = hit.get("link", "")
            if not url:
                continue
            domain = domain_of(url)
            if not domain or domain == own_domain:
                continue
            # a community's identity is its subreddit, not reddit.com
            name = _subreddit_of(url) if kind == KIND_COMMUNITY else domain
            if not name:
                continue
            venue = venues.setdefault(_venue_key(kind, name), {
                "kind": kind,
                "name": name,
                "url": f"https://reddit.com/{name}" if name.startswith("r/") else f"https://{domain}",
                "cited_where_absent": 0,
                "found_via": [],
                "examples": [],
            })
            if "live-search" not in venue["found_via"]:
                venue["found_via"].append("live-search")
            if len(venue["examples"]) < _MAX_EXAMPLES:
                venue["examples"].append({"title": hit.get("title", ""), "url": url})
            # a brand result on a review platform means the profile exists
            if kind == KIND_REVIEW and domain in REVIEW_PLATFORMS:
                venue["brand_present"] = True

    # Presence on these is an inclusion requirement, so an absent profile is
    # itself an action — the venue belongs in the list precisely because the
    # brand is missing from it.
    for platform in REVIEW_PLATFORMS:
        venues.setdefault(_venue_key(KIND_REVIEW, platform), {
            "kind": KIND_REVIEW, "name": platform, "url": f"https://{platform}",
            "cited_where_absent": 0, "found_via": ["known-platform"],
            "examples": [], "brand_present": False,
        })

    ranked = sorted(
        venues.values(),
        key=lambda v: (
            # proven to feed the answers we lose beats merely existing
            -v.get("cited_where_absent", 0),
            -len(v.get("examples") or []),
            v["name"],
        ),
    )
    return {
        "category": category,
        "venues": ranked,
        "counts": _counts(ranked),
        "searched": searched,
        "errors": errors,
        # a plan built with no live search is legitimate but narrower — the
        # strategist and the panel both need to know which one they have
        "complete": searched > 0 and not errors,
    }


def _counts(venues: list[dict]) -> dict[str, int]:
    counts: dict[str, int] = defaultdict(int)
    for venue in venues:
        counts[venue["kind"]] += 1
    return dict(counts)


def allowed_names(discovery: dict) -> set[str]:
    """Venue names the strategist may cite. Lower-cased: the model reproduces
    the name it was given, and case drift must not read as a hallucination."""
    return {(v.get("name") or "").lower() for v in discovery.get("venues") or [] if v.get("name")}


def venue_by_name(discovery: dict, name: str) -> dict[str, Any] | None:
    target = (name or "").lower()
    for venue in discovery.get("venues") or []:
        if (venue.get("name") or "").lower() == target:
            return venue
    return None
